### ISSUE TITLE
Rebuild from Fyb3roptik's fork which fixed logos

### ISSUE THREAD

**Issue by hacktek** [dnsforge-repo/xteve#13]
Hi! Any chance that we can get a docker tag that uses this fork instead?

https://github.com/Fyb3roptik/PlexTeVe

Logos appear to be broken in the official repo.

If not, if you could share your docker-compose that'd be great.

**Comment by dnsforge-repo** [comment]
@hacktek There are no issues with logos in the upstream repo. 

Here is a docker compose you can try for dnsforge docker:

```
xteve:
    image: dnsforge/xteve:latest
    container_name: xteve
    net: host
    environment:
      - XTEVE_USER=xteve
      - XTEVE_UID=31337
      - XTEVE_GID=31337
      - TZ=America/New_York
      - XTEVE_PORT=34400
      - XTEVE_BRANCH=master
      - XTEVE_DEBUG=1
      - XTEVE_API=1
    volumes:
      - /path/to/xteve:/home/xteve/conf
      - /path/to/guide2go:/home/xteve/guide2go/conf
# Host mode is recommended. To configure port bindings set "net" to "bridge"
#    ports:
#      - "34400:34400"
    restart: unless-stopped
```
